# pandas: biblioteca para análisis y manipulación de datos

<div style="display: flex; justify-content: flex-start;">
  <a href="https://colab.research.google.com/github/tpb708-programacionsig/2026-i/blob/main/contenidos/iii-analisis-visualizacion-datos/01-pandas.ipynb">
    <img src="https://img.shields.io/badge/Abrir%20en-Colab-F9AB00?logo=googlecolab&logoColor=white" alt="Abrir en Colab" style="margin: 0;">
  </a>
</div>

## Trabajo previo

### Lecturas

McKinney, W. (2022). *Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter* (3a ed.). O'Reilly Media. [https://wesmckinney.com/book/](https://wesmckinney.com/book/)
\
\
Kaggle. (s. f.). *Pandas*. Kaggle Learn. [https://www.kaggle.com/learn/pandas](https://www.kaggle.com/learn/pandas)

### Otros recursos

Documentación oficial de pandas\
[pandas documentation](https://pandas.pydata.org/docs/)

  - [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)
  - [User Guide](https://pandas.pydata.org/docs/user_guide/index.html)
  - [API reference](https://pandas.pydata.org/docs/reference/index.html)

Hoja de referencia oficial\
[pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

## Introducción

[pandas](https://pandas.pydata.org/) es una biblioteca de Python para análisis y manipulación de datos. Fue creada por Wes McKinney en 2008. El nombre "pandas" puede considerarse un acrónimo de *Panel Data* o de *Python Data Analysis*.

Como su estructura principal, pandas implementa el `dataframe`, el cual es un arreglo rectangular de datos, organizado en filas y columnas. pandas proporciona también una gran cantidad de funciones para limpiar, procesar, analizar y visualizar datos en dataframes.

## Carga

In [1]:
# Carga de pandas con el alias pd
import pandas as pd

## Configuración

El método [pandas.set_option()](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html) se utiliza para configurar diversas opciones que controlan el comportamiento de pandas y la visualización de datos. Estas opciones permiten personalizar aspectos como:

- El número de filas y columnas que se muestran al desplegar conjuntos de datos.
- La precisión al mostrar números decimales.
- El ancho máximo de filas y columnas.
- El formato de la fecha y la hora.

In [2]:
# Configuración de pandas para mostrar separadores de miles y 2 dígitos decimales
# Esto también evita la notación científica

pd.set_option('display.float_format', '{:,.2f}'.format)

Otras funciones relacionadas con la configuración de pandas:

- [pandas.describe_option()](https://pandas.pydata.org/docs/reference/api/pandas.describe_option.html): muestra información sobre una opción (ej. `pd.describe_option('display.max_rows')`). `pd.describe_option()` describe todas las opciones.
- [pandas.get_option()](https://pandas.pydata.org/docs/reference/api/pandas.get_option.html): muestra el valor actual de una opción de configuración (ej. `pd.get_option('display.max_rows')`).
- [pandas.reset_option()](https://pandas.pydata.org/docs/reference/api/pandas.reset_option.html): reestablece el valor por defecto de una opción de configuración (ej. `pd.reset_option('display.max_rows')`). `pd.reset_option('all')` reestablece todas las opciones.

Debe tenerse en cuenta que el uso de estas funciones aplica para toda una sesión de pandas y no, por ejemplo, para conjuntos de datos específicos.

## Estructuras de datos
Las dos principales estructuras de datos de pandas son las `series` y los `dataframes`.

### Series
Las [`series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html?highlight=series#pandas.Series) son arreglos unidimensionales que contienen datos de cualquier tipo.

In [3]:
# Definición de una serie a partir de una lista

lista_primos = [2, 3, 5, 7, 11]
serie_primos = pd.Series(lista_primos)

print(serie_primos)

0     2
1     3
2     5
3     7
4    11
dtype: int64

Al igual que otras estructuras de datos de Python (ej. tuplas, listas), cada elemento de una serie tiene un índice (i.e. una posición). El índice del primer elemento es 0, el del segundo elemento es 1 y así sucesivamente.

In [4]:
# Primer elemento
print("Primer elemento:", serie_primos[0])

# Segundo elemento
print("Segundo elemento:", serie_primos[1])

Primer elemento: 2
Segundo elemento: 3

A diferencia de las tuplas y las listas, las series pueden tener índices no numéricos, a los cuales se les llama etiquetas.

In [5]:
# Índices de una serie con etiquetas personalizadas
serie_primos = pd.Series(lista_primos, index = ["A", "B", "C", "D", "E"])

serie_primos

A     2
B     3
C     5
D     7
E    11
dtype: int64

In [6]:
# Elemento en la posición B
print("Elemento en B:", serie_primos["B"])

# Elemento en la posición D
print("Elemento en D:", serie_primos["D"])

Elemento en B: 3
Elemento en D: 7

**Ejercicios**

1. Cree una serie que contenga los montos de ventas de una tienda para los 12 meses del año. Utilice los nombres de los meses como índices.

### Dataframes
Los [`dataframes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) son estructuras de datos multidimensionales compuestas por filas y columnas. Un dataframe puede verse como una tabla cuyas columnas se implementan como series.

In [7]:
# Dataframe generado a partir de un diccionario

diccionario_paises = {
  "pais": ["PA", "CR", "NI"],
  "poblacion": [4246439, 5047561, 6545502]
}

df_paises = pd.DataFrame(diccionario_paises)

df_paises

  pais  poblacion
0   PA    4246439
1   CR    5047561
2   NI    6545502

La propiedad **iloc** retorna una o más filas de un dataframe, de acuerdo con un índice o una lista de índices.

In [8]:
# Segunda fila
df_paises.iloc[1]

pais              CR
poblacion    5047561
Name: 1, dtype: object

In [9]:
# Segunda y tercera fila
df_paises.loc[[1, 2]]

  pais  poblacion
1   CR    5047561
2   NI    6545502

Los índices de los dataframes también pueden etiquetarse.

In [10]:
# Dataframe con índices etiquetados

df_paises = pd.DataFrame(diccionario_paises, index=["pais_0", "pais_1", "pais_2"])

df_paises

       pais  poblacion
pais_0   PA    4246439
pais_1   CR    5047561
pais_2   NI    6545502

La propiedad **loc** retorna una o más filas de un dataframe, de acuerdo con sus etiquetas.

In [11]:
# Fila en "pais_0"
df_paises.loc["pais_0"]

pais              PA
poblacion    4246439
Name: pais_0, dtype: object

## Operaciones básicas

Seguidamente, se describen y ejemplifican algunas de las funciones básicas que pueden realizarse en un dataframe de pandas.

En los siguientes ejemplos, se utilizará un conjunto de datos de países descargado de [Natural Earth](https://www.naturalearthdata.com/).

### Carga de datos

El método [`pandas.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv) carga un archivo de valores separados por comas (CSV) en un dataframe.

In [12]:
# Carga de un archivo CSV remoto en un dataframe

paises = pd.read_csv(
    "https://raw.githubusercontent.com/pf3311-cienciadatosgeoespaciales/2025-ii/refs/heads/main/datos/natural-earth/paises.csv"
)

**Ejercicios**

1. Descargue en su computadora el archivo `paises.csv` y cárguelo en otro dataframe.

### Obtención de información general

El método [`pandas.DataFrame.info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) despliega un resumen de información sobre un dataframe.

In [13]:
# Información general sobre un dataframe

paises.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ADM0_ISO    201 non-null    str
 1   NAME        201 non-null    str
 2   CONTINENT   201 non-null    str
 3   REGION_UN   201 non-null    str
 4   SUBREGION   201 non-null    str
 5   REGION_WB   201 non-null    str
 6   ECONOMY     201 non-null    str
 7   INCOME_GRP  201 non-null    str
 8   POP_EST     201 non-null    float64
 9   GDP_MD      201 non-null    int64
dtypes: float64(1), int64(1), str(8)
memory usage: 15.8 KB

Además de `info()`, pandas ofrece varios atributos y métodos útiles para explorar rápidamente la estructura y el contenido de un dataframe.

#### Dimensiones, tipos de datos y columnas

El atributo [`pandas.DataFrame.shape`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html) retorna una tupla con el número de filas y de columnas.

In [14]:
# Número de filas y columnas

paises.shape

(201, 10)

El atributo [`pandas.DataFrame.dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html) muestra el tipo de dato de cada columna.

In [15]:
# Tipos de datos de las columnas

paises.dtypes

ADM0_ISO          str
NAME              str
CONTINENT         str
REGION_UN         str
SUBREGION         str
REGION_WB         str
ECONOMY           str
INCOME_GRP        str
POP_EST       float64
GDP_MD          int64
dtype: object

El atributo [`pandas.DataFrame.columns`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html) retorna los nombres de las columnas.

In [16]:
# Nombres de las columnas

paises.columns

Index(['ADM0_ISO', 'NAME', 'CONTINENT', 'REGION_UN', 'SUBREGION', 'REGION_WB',
       'ECONOMY', 'INCOME_GRP', 'POP_EST', 'GDP_MD'],
      dtype='str')

#### Estadísticas descriptivas

El método [`pandas.DataFrame.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) genera estadísticas descriptivas (conteo, media, desviación estándar, mínimo, cuartiles y máximo) para las columnas numéricas del dataframe.

In [17]:
# Estadísticas descriptivas de las columnas numéricas

paises.describe()

               POP_EST        GDP_MD
count           201.00        201.00
mean     38,175,753.98    439,027.50
std     143,094,549.78  1,922,726.62
min             825.00        -99.00
25%       1,394,973.00      7,188.00
50%       8,082,366.00     31,471.00
75%      26,969,307.00    225,700.00
max   1,405,862,845.00 21,542,705.00

Por defecto, `describe()` solo considera columnas numéricas. Mediante el argumento `include='all'` pueden incluirse también las columnas no numéricas (para estas se muestran, entre otras, el número de valores únicos y el valor más frecuente).

In [18]:
# Estadísticas descriptivas de todas las columnas

paises.describe(include='all')

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
count,201,201,201,201,201,201,201,201,201.00,201.00
unique,197,201,8,6,23,8,7,5,NaN,NaN
top,CYP,Indonesia,Africa,Africa,Western Asia,Europe & Central Asia,6. Developing region,4. Lower middle income,NaN,NaN
freq,3,1,54,56,19,56,81,54,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"38,175,753.98","439,027.50"
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"143,094,549.78","1,922,726.62"
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,825.00,-99.00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,394,973.00","7,188.00"
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"8,082,366.00","31,471.00"
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"26,969,307.00","225,700.00"
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,405,862,845.00","21,542,705.00"

#### Distribución de valores

El método [`pandas.Series.value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) retorna el conteo de valores únicos de una columna (Serie), ordenados de mayor a menor frecuencia. Es especialmente útil para conocer la distribución de valores en columnas categóricas.

In [19]:
# Número de países por continente

paises['CONTINENT'].value_counts()

CONTINENT
Africa                     54
Asia                       49
Europe                     45
North America              23
Oceania                    14
South America              12
Seven seas (open ocean)     3
Antarctica                  1
Name: count, dtype: int64

Como ejemplo adicional, el número de países por subregión:

In [20]:
# Número de países por subregión

paises['SUBREGION'].value_counts()

SUBREGION
Western Asia                 19
Eastern Africa               19
Southern Europe              16
Western Africa               16
Caribbean                    13
South America                12
South-Eastern Asia           11
Northern Europe              10
Eastern Europe               10
Southern Asia                 9
Western Europe                9
Middle Africa                 9
Central America               8
Northern Africa               7
Eastern Asia                  6
Southern Africa               5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Northern America              2
Australia and New Zealand     2
Antarctica                    1
Name: count, dtype: int64

### Despliegue de datos

Los datos contenidos en un dataframe pueden visualizarse con la función `print()`. En un cuaderno de notas, basta también con ejecutar una celda con el nombre del dataframe. Esta última opción genera una salida más legible.

In [21]:
# Despliegue de los datos de un dataframe

paises

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
0,IDN,Indonesia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,4. Emerging region: MIKT,4. Lower middle income,"270,625,568.00",1119190
1,MYS,Malaysia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,6. Developing region,3. Upper middle income,"31,949,777.00",364681
2,CHL,Chile,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"18,952,038.00",282318
3,BOL,Bolivia,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,4. Lower middle income,"11,513,100.00",40895
4,PER,Peru,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"32,510,453.00",226848
...,...,...,...,...,...,...,...,...,...,...
196,NRU,Nauru,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,4. Lower middle income,"12,581.00",118
197,FSM,Micronesia,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,4. Lower middle income,"113,815.00",401
198,VUT,Vanuatu,Oceania,Oceania,Melanesia,East Asia & Pacific,7. Least developed region,4. Lower middle income,"299,882.00",934
199,PLW,Palau,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,3. Upper middle income,"18,008.00",268
200,BHR,Bahrain,Asia,Asia,Western Asia,Middle East & North Africa,6. Developing region,2. High income: nonOECD,"1,641,172.00",38574

Es posible que la cantidad de filas sea muy grande para desplegarse completamente en la pantalla, por lo que es usual emplear algunos métodos para limitarla.

#### `head()` - primeras filas

El método [`pandas.DataFrame.head()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html) retorna las primeras n filas de un dataframe (por defecto, n=5).

In [22]:
# Primeras 5 filas de un dataframe

paises.head()

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
0,IDN,Indonesia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,4. Emerging region: MIKT,4. Lower middle income,"270,625,568.00",1119190
1,MYS,Malaysia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,6. Developing region,3. Upper middle income,"31,949,777.00",364681
2,CHL,Chile,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"18,952,038.00",282318
3,BOL,Bolivia,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,4. Lower middle income,"11,513,100.00",40895
4,PER,Peru,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"32,510,453.00",226848

#### `tail()` - últimas filas

El método [`pandas.DataFrame.tail()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html) retorna las últimas n filas de un dataframe (por defecto, n=5).

In [23]:
# Últimas 10 filas de un dataframe

paises.tail(10)

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
191,TON,Tonga,Oceania,Oceania,Polynesia,East Asia & Pacific,6. Developing region,4. Lower middle income,"104,494.00",512
192,WSM,Samoa,Oceania,Oceania,Polynesia,East Asia & Pacific,7. Least developed region,4. Lower middle income,"197,097.00",852
193,SLB,Solomon Is.,Oceania,Oceania,Melanesia,East Asia & Pacific,7. Least developed region,4. Lower middle income,"669,823.00",1589
194,TUV,Tuvalu,Oceania,Oceania,Polynesia,East Asia & Pacific,7. Least developed region,3. Upper middle income,"11,646.00",47
195,MDV,Maldives,Seven seas (open ocean),Asia,Southern Asia,South Asia,6. Developing region,3. Upper middle income,"530,953.00",5642
196,NRU,Nauru,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,4. Lower middle income,"12,581.00",118
197,FSM,Micronesia,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,4. Lower middle income,"113,815.00",401
198,VUT,Vanuatu,Oceania,Oceania,Melanesia,East Asia & Pacific,7. Least developed region,4. Lower middle income,"299,882.00",934
199,PLW,Palau,Oceania,Oceania,Micronesia,East Asia & Pacific,6. Developing region,3. Upper middle income,"18,008.00",268
200,BHR,Bahrain,Asia,Asia,Western Asia,Middle East & North Africa,6. Developing region,2. High income: nonOECD,"1,641,172.00",38574

#### `sample()` - muestra aleatoria de filas

El método [`pandas.DataFrame.sample()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html) retorna una muestra aleatoria de n filas de un dataframe (por defecto, n=1).

In [24]:
# Muestra aleatoria de 3 filas de un dataframe

paises.sample(3)

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
5,ARG,Argentina,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"44,938,712.00",445445
173,SYC,Seychelles,Seven seas (open ocean),Africa,Eastern Africa,Sub-Saharan Africa,6. Developing region,3. Upper middle income,"97,625.00",1703
147,USA,United States of America,North America,Americas,Northern America,North America,1. Developed region: G7,1. High income: OECD,"331,595,460.00",21542705

### Creación de subconjuntos

Una de las operaciones más comunes de manipulación y análisis de datos es la creación de subconjuntos. En el caso de un dataframe, estos subconjuntos pueden ser de filas, de columnas o de ambas a la vez. Pueden crearse de varias formas.

#### Mediante índices numéricos

La propiedad [`pandas.DataFrame.iloc`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) permite seleccionar filas y columnas de un dataframe por sus índices numéricos.

Índice de una fila:

In [25]:
# Fila 0
paises.iloc[0]

ADM0_ISO                           IDN
NAME                         Indonesia
CONTINENT                         Asia
REGION_UN                         Asia
SUBREGION           South-Eastern Asia
REGION_WB          East Asia & Pacific
ECONOMY       4. Emerging region: MIKT
INCOME_GRP      4. Lower middle income
POP_EST                 270,625,568.00
GDP_MD                         1119190
Name: 0, dtype: object

Rango de filas:

In [26]:
# Filas entre la 5 (inclusive) y la 7 (inclusive)
paises.iloc[5:8]

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
5,ARG,Argentina,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"44,938,712.00",445445
6,GBR,United Kingdom,Europe,Europe,Northern Europe,Europe & Central Asia,1. Developed region: G7,1. High income: OECD,"67,366,465.00",2863166
7,CYP,Cyprus,Asia,Asia,Western Asia,Europe & Central Asia,6. Developing region,2. High income: nonOECD,"1,198,575.00",24948

Lista de índices de filas:

In [27]:
# Filas 3, 5 y 7
paises.iloc[[3, 5, 7]]

,ADM0_ISO,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
3,BOL,Bolivia,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,4. Lower middle income,"11,513,100.00",40895
5,ARG,Argentina,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"44,938,712.00",445445
7,CYP,Cyprus,Asia,Asia,Western Asia,Europe & Central Asia,6. Developing region,2. High income: nonOECD,"1,198,575.00",24948

#### Mediante etiquetas

La propiedad [`pandas.DataFrame.loc`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) permite seleccionar filas y columnas de un dataframe por sus etiquetas.

El método [`pandas.DataFrame.set_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) crea índices (etiquetas en las filas) para un dataframe con base en columnas existentes.

In [28]:
# Se usa la columna ADM0_ISO como índice
paises.set_index('ADM0_ISO', inplace=True)

paises.iloc[0:5]

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
IDN,Indonesia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,4. Emerging region: MIKT,4. Lower middle income,"270,625,568.00",1119190
MYS,Malaysia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,6. Developing region,3. Upper middle income,"31,949,777.00",364681
CHL,Chile,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"18,952,038.00",282318
BOL,Bolivia,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,4. Lower middle income,"11,513,100.00",40895
PER,Peru,South America,Americas,South America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"32,510,453.00",226848

Si se desea reestablecer el índice al numérico predeterminado, puede utilizarse el método [`pandas.DataFrame.reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html).

Una vez que se han creado las etiquetas, puede usarse `loc` para seleccionarlas.

In [29]:
# Fila correspondiente a Costa Rica
paises.loc['CRI']

NAME                         Costa Rica
CONTINENT                 North America
REGION_UN                      Americas
SUBREGION               Central America
REGION_WB     Latin America & Caribbean
ECONOMY         5. Emerging region: G20
INCOME_GRP       3. Upper middle income
POP_EST                    5,047,561.00
GDP_MD                            61801
Name: CRI, dtype: object

In [30]:
# Lista de filas correspondientes a Costa Rica, Nicaragua y Panamá
paises.loc[['CRI', 'NIC', 'PAN']]

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
CRI,Costa Rica,North America,Americas,Central America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"5,047,561.00",61801
NIC,Nicaragua,North America,Americas,Central America,Latin America & Caribbean,6. Developing region,4. Lower middle income,"6,545,502.00",12520
PAN,Panama,North America,Americas,Central America,Latin America & Caribbean,6. Developing region,3. Upper middle income,"4,246,439.00",66800

In [31]:
# Lista de etiquetas de filas y lista de etiquetas de columnas
paises.loc[['CRI', 'NIC', 'PAN'], ['NAME', 'POP_EST']]

                NAME      POP_EST
ADM0_ISO
CRI       Costa Rica 5,047,561.00
NIC        Nicaragua 6,545,502.00
PAN           Panama 4,246,439.00

In [32]:
# Nombres y poblaciones de países de América Central
poblaciones_america_central = paises.loc[['PAN', 'CRI', 'NIC', 'HND', 'SLV', 'GTM', 'BLZ'], ['NAME', 'POP_EST']]

poblaciones_america_central

                 NAME       POP_EST
ADM0_ISO
PAN            Panama  4,246,439.00
CRI        Costa Rica  5,047,561.00
NIC         Nicaragua  6,545,502.00
HND          Honduras  9,746,117.00
SLV       El Salvador  6,453,553.00
GTM         Guatemala 16,604,026.00
BLZ            Belize    390,353.00

**Ejercicios**

1. Seleccione los países de la península ibérica y las columnas correspondientes a sus nombres y a su producto interno bruto.

#### Mediante expresiones lógicas

Un dataframe puede filtrarse mediante expresiones lógicas, las cuales pueden incluir los operadores:

Y lógico (*AND*): `&`  
O lógico (*OR*): `|`  
No lógico (*NOT*): `~`

In [33]:
# Países con más de 200 millones de habitantes
paises_muy_poblados = paises[paises['POP_EST'] > 200000000]

paises_muy_poblados

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
IDN,Indonesia,Asia,Asia,South-Eastern Asia,East Asia & Pacific,4. Emerging region: MIKT,4. Lower middle income,"270,625,568.00",1119190
IND,India,Asia,Asia,Southern Asia,South Asia,3. Emerging region: BRIC,4. Lower middle income,"1,366,417,754.00",2868929
CHN,China,Asia,Asia,Eastern Asia,East Asia & Pacific,3. Emerging region: BRIC,3. Upper middle income,"1,405,862,845.00",14762473
BRA,Brazil,South America,Americas,South America,Latin America & Caribbean,3. Emerging region: BRIC,3. Upper middle income,"211,049,527.00",1839758
NGA,Nigeria,Africa,Africa,Western Africa,Sub-Saharan Africa,5. Emerging region: G20,4. Lower middle income,"200,963,599.00",448120
PAK,Pakistan,Asia,Asia,Southern Asia,South Asia,5. Emerging region: G20,4. Lower middle income,"216,565,318.00",278221
USA,United States of America,North America,Americas,Northern America,North America,1. Developed region: G7,1. High income: OECD,"331,595,460.00",21542705

In [34]:
# Países con más de 200 millones de habitantes, incluyendo solo NAME, CONTINENT y POP_EST
paises_muy_poblados = paises.loc[paises['POP_EST'] > 200000000, ['NAME', 'CONTINENT', 'POP_EST']]

paises_muy_poblados

                              NAME      CONTINENT          POP_EST
ADM0_ISO
IDN                      Indonesia           Asia   270,625,568.00
IND                          India           Asia 1,366,417,754.00
CHN                          China           Asia 1,405,862,845.00
BRA                         Brazil  South America   211,049,527.00
NGA                        Nigeria         Africa   200,963,599.00
PAK                       Pakistan           Asia   216,565,318.00
USA       United States of America  North America   331,595,460.00

In [35]:
# Países asiáticos con más de 200 millones de habitantes, incluyendo solo NAME, CONTINENT y POP_EST
paises_asiaticos_muy_poblados = paises.loc[
    (paises['POP_EST'] > 200000000) & (paises['CONTINENT'] == 'Asia'), 
    ['NAME', 'CONTINENT', 'POP_EST']
]

paises_asiaticos_muy_poblados

               NAME CONTINENT          POP_EST
ADM0_ISO
IDN       Indonesia      Asia   270,625,568.00
IND           India      Asia 1,366,417,754.00
CHN           China      Asia 1,405,862,845.00
PAK        Pakistan      Asia   216,565,318.00

In [36]:
# Países asiáticos o africanos con más de 200 millones de habitantes, incluyendo solo NAME, CONTINENT y POP_EST
paises_asiaticos_africanos_muy_poblados = paises.loc[
    (paises['POP_EST'] > 200000000) & ((paises['CONTINENT'] == 'Asia') | (paises['CONTINENT'] == 'Africa')), 
    ['NAME', 'CONTINENT', 'POP_EST']
]

paises_asiaticos_africanos_muy_poblados

               NAME CONTINENT          POP_EST
ADM0_ISO
IDN       Indonesia      Asia   270,625,568.00
IND           India      Asia 1,366,417,754.00
CHN           China      Asia 1,405,862,845.00
NGA         Nigeria    Africa   200,963,599.00
PAK        Pakistan      Asia   216,565,318.00

#### Métodos `head()`, `tail()` y `sample()`

Los métodos `head()`, `tail()` y `sample()`, descritos anteriormente, también pueden emplearse para crear subconjuntos.

**Ejercicios**

1. Cree un subconjunto de los países con producto interno bruto (`GDP_MD`) menor a 1000 millones de dólares.
2. Cree un subconjunto de los países con producto interno bruto menor a 1000 millones de dólares y con más de un millón de habitantes.
3. Cree un subconjunto de los países de América Central, excepto Belice.
4. Cree un subconjunto de los siete países de América Central y, además, República Dominicana.

### Ordenamiento

El método [`pandas.DataFrame.sort_values()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) ordena un dataframe de pandas por una o por varias columnas, en orden ascendente o descendente.

In [37]:
# Ordenamiento ascendente de países por nombre
paises.sort_values(by='NAME')

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
AFG,Afghanistan,Asia,Asia,Southern Asia,South Asia,7. Least developed region,5. Low income,"38,041,754.00",19291
ALB,Albania,Europe,Europe,Southern Europe,Europe & Central Asia,6. Developing region,4. Lower middle income,"2,854,191.00",15279
DZA,Algeria,Africa,Africa,Northern Africa,Middle East & North Africa,6. Developing region,3. Upper middle income,"43,053,054.00",171091
AND,Andorra,Europe,Europe,Southern Europe,Europe & Central Asia,2. Developed region: nonG7,2. High income: nonOECD,"77,142.00",3154
AGO,Angola,Africa,Africa,Middle Africa,Sub-Saharan Africa,7. Least developed region,3. Upper middle income,"31,825,295.00",88815
...,...,...,...,...,...,...,...,...,...
B28,W. Sahara,Africa,Africa,Northern Africa,Middle East & North Africa,7. Least developed region,5. Low income,"603,253.00",907
YEM,Yemen,Asia,Asia,Western Asia,Middle East & North Africa,7. Least developed region,4. Lower middle income,"29,161,922.00",22581
ZMB,Zambia,Africa,Africa,Eastern Africa,Sub-Saharan Africa,7. Least developed region,4. Lower middle income,"17,861,030.00",23309
ZWE,Zimbabwe,Africa,Africa,Eastern Africa,Sub-Saharan Africa,5. Emerging region: G20,5. Low income,"14,645,468.00",21440
SWZ,eSwatini,Africa,Africa,Southern Africa,Sub-Saharan Africa,6. Developing region,4. Lower middle income,"1,148,130.00",4471

In [38]:
# Ordenamiento ascendente de países por nombre y despliegue de las 5 primeras filas
paises.sort_values(by='NAME').head()

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
AFG,Afghanistan,Asia,Asia,Southern Asia,South Asia,7. Least developed region,5. Low income,"38,041,754.00",19291
ALB,Albania,Europe,Europe,Southern Europe,Europe & Central Asia,6. Developing region,4. Lower middle income,"2,854,191.00",15279
DZA,Algeria,Africa,Africa,Northern Africa,Middle East & North Africa,6. Developing region,3. Upper middle income,"43,053,054.00",171091
AND,Andorra,Europe,Europe,Southern Europe,Europe & Central Asia,2. Developed region: nonG7,2. High income: nonOECD,"77,142.00",3154
AGO,Angola,Africa,Africa,Middle Africa,Sub-Saharan Africa,7. Least developed region,3. Upper middle income,"31,825,295.00",88815

In [39]:
# Ordenamiento descendente de países por nombre y despliegue de las 5 primeras filas
paises.sort_values(by='NAME', ascending=False).head()

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD
ADM0_ISO,,,,,,,,,
SWZ,eSwatini,Africa,Africa,Southern Africa,Sub-Saharan Africa,6. Developing region,4. Lower middle income,"1,148,130.00",4471
ZWE,Zimbabwe,Africa,Africa,Eastern Africa,Sub-Saharan Africa,5. Emerging region: G20,5. Low income,"14,645,468.00",21440
ZMB,Zambia,Africa,Africa,Eastern Africa,Sub-Saharan Africa,7. Least developed region,4. Lower middle income,"17,861,030.00",23309
YEM,Yemen,Asia,Asia,Western Asia,Middle East & North Africa,7. Least developed region,4. Lower middle income,"29,161,922.00",22581
B28,W. Sahara,Africa,Africa,Northern Africa,Middle East & North Africa,7. Least developed region,5. Low income,"603,253.00",907

In [40]:
# Ordenamiento de países por continente y nombre
paises.sort_values(by=['CONTINENT', 'NAME'], ascending=[True, True])[['CONTINENT', 'NAME']]

              CONTINENT          NAME
ADM0_ISO
DZA              Africa       Algeria
AGO              Africa        Angola
BEN              Africa         Benin
BWA              Africa      Botswana
BFA              Africa  Burkina Faso
...                 ...           ...
PRY       South America      Paraguay
PER       South America          Peru
SUR       South America      Suriname
URY       South America       Uruguay
VEN       South America     Venezuela

[201 rows x 2 columns]

**Ejercicios**

1. Cree un subconjunto de todos los países del mundo ordenado descendentemente por la cantidad de habitantes.
2. Cree un subconjunto de todos los países del mundo ordenado ascendentemente por el producto interno bruto.

### Creación y modificación de columnas

En un dataframe, pueden crearse o modificarse columnas de varias formas. Una de las más comunes es a través de operaciones con otras columnas.

#### Ejemplo: PIB per cápita

En el dataframe `paises` puede crearse una nueva columna llamada `GDP_MD_PC` con el resultado del cálculo del [Producto Interno Bruto (PIB) per cápita](https://es.wikipedia.org/wiki/Renta_per_c%C3%A1pita) para cada país.

In [41]:
# Creación de la columna GDP_PC (PIB per cápita en dólares)
paises['GDP_PC'] = (paises['GDP_MD'] * 1000000) / paises['POP_EST']

Para modularizar el código, es conveniente crear una función que realice el cálculo del PIB per cápita.

In [42]:
def pib_per_capita(pib, poblacion):
    """
    Retorna el PIB per cápita dados el PIB de un país (en millones de dólares) y su población.
    """

    return (pib * 1000000) / poblacion

In [43]:
# Creación de la columna GDP_PC (PIB per cápita en dólares)
# mediante la función pib_per_capita()
paises['GDP_PC'] = pib_per_capita(paises['GDP_MD'], paises['POP_EST'])

In [44]:
# Despliegue de la nueva columna
paises[['NAME', 'GDP_MD', 'POP_EST', 'GDP_PC']]

                NAME   GDP_MD        POP_EST    GDP_PC
ADM0_ISO
IDN        Indonesia  1119190 270,625,568.00  4,135.57
MYS         Malaysia   364681  31,949,777.00 11,414.20
CHL            Chile   282318  18,952,038.00 14,896.45
BOL          Bolivia    40895  11,513,100.00  3,552.04
PER             Peru   226848  32,510,453.00  6,977.69
...              ...      ...            ...       ...
NRU            Nauru      118      12,581.00  9,379.22
FSM       Micronesia      401     113,815.00  3,523.26
VUT          Vanuatu      934     299,882.00  3,114.56
PLW            Palau      268      18,008.00 14,882.27
BHR          Bahrain    38574   1,641,172.00 23,503.93

[201 rows x 4 columns]

#### Aplicación de funciones: `map()` y `apply()`

Cuando se requiere aplicar una función a cada elemento de una Serie, a cada valor de un índice, o a cada fila o columna de un dataframe, pandas ofrece los métodos `map()` y `apply()`. Resultan especialmente útiles cuando la lógica no puede expresarse con operaciones vectorizadas como las del ejemplo anterior.

El método [`pandas.Series.map()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html) aplica una función a cada elemento de una Serie y retorna una nueva Serie con los resultados. El método [`pandas.Index.map()`](https://pandas.pydata.org/docs/reference/api/pandas.Index.map.html) opera de manera análoga sobre un índice.

Por ejemplo, para obtener la cantidad de caracteres del nombre de cada país:

In [45]:
# Longitud del nombre de cada país

paises['NAME'].map(len).head()

ADM0_ISO
IDN    9
MYS    8
CHL    5
BOL    7
PER    4
Name: NAME, dtype: int64

El método [`pandas.DataFrame.apply()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) es más general: aplica una función a lo largo de un eje del dataframe, lo que permite trabajar con varias columnas a la vez. Con `axis=1` la función recibe cada fila como argumento; con `axis=0` (valor por defecto) recibe cada columna.

Para definir funciones cortas de un solo uso, Python ofrece la sintaxis [`lambda`](https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions), que crea una **función anónima** en una sola línea. Por ejemplo, `lambda x: x * 2` es equivalente a una función que recibe un argumento `x` y retorna `x * 2`. Esta sintaxis es habitual con `map()` y `apply()` cuando la lógica es sencilla y no amerita definir una función con `def`.

Por ejemplo, el cálculo del PIB per cápita puede expresarse también con `apply()` fila por fila, reutilizando la función `pib_per_capita()` definida anteriormente:

In [46]:
# PIB per cápita con apply() (equivalente al cálculo vectorizado anterior)

paises[['GDP_MD', 'POP_EST']].apply(
    lambda fila: pib_per_capita(fila['GDP_MD'], fila['POP_EST']),
    axis=1
).head()

ADM0_ISO
IDN    4,135.57
MYS   11,414.20
CHL   14,896.45
BOL    3,552.04
PER    6,977.69
dtype: float64

La operación vectorizada es más eficiente cuando es posible expresarla de esa forma. Sin embargo, `map()` y `apply()` resultan indispensables cuando la lógica por elemento o por fila es más compleja — por ejemplo, cuando requiere consultar un servicio externo para cada país, como se mostrará a continuación.

#### Ejemplo: idiomas oficiales

Para crear una nueva columna llamada `LANGUAGES`, con los idiomas oficiales de cada país, se define una función llamada `obtener_idiomas_pais()`, la cual recibe como entrada el código [ISO 3166-1 alpha-3 (cca3)](https://es.wikipedia.org/wiki/ISO_3166-1_alfa-3) del país (el cual se encuentra en el índice del dataframe `paises`) y consulta el API [REST Countries](https://restcountries.com/) para retornar una hilera de texto con los nombres de los idiomas.

In [47]:
import requests

def obtener_idiomas_pais(cca3):
    """
    Obtiene una cadena con la lista de lenguajes oficiales de un país dado su código cca3.
    """

    # URL del API REST Countries
    url = f'https://restcountries.com/v3.1/alpha/{cca3}'
    
    # Respuesta del API a la solicitud
    respuesta = requests.get(url)
    
    # Revisión de la respuesta
    if respuesta.status_code == 200:
        datos = respuesta.json()
        
        if datos and 'languages' in datos[0]:
            lenguajes = datos[0]['languages']
            lista_lenguajes = list(lenguajes.values())
            return ', '.join(lista_lenguajes)
        else:
            return None
    else:
        return None

Para asignar un valor de `LANGUAGES` a cada país, se aplica la función `obtener_idiomas_pais()` a cada elemento del índice del dataframe (que contiene el código `ADM0_ISO`) mediante [`pandas.Index.map()`](https://pandas.pydata.org/docs/reference/api/pandas.Index.map.html):

In [48]:
# Creación de la columna LANGUAGES mediante la función obtener_idiomas_pais()
paises['LANGUAGES'] = paises.index.map(obtener_idiomas_pais)

In [49]:
# Despliegue de la nueva columna
paises[['NAME', 'LANGUAGES']]

                NAME                          LANGUAGES
ADM0_ISO
IDN        Indonesia                         Indonesian
MYS         Malaysia                     English, Malay
CHL            Chile                            Spanish
BOL          Bolivia  Aymara, Guaraní, Quechua, Spanish
PER             Peru           Aymara, Quechua, Spanish
...              ...                                ...
NRU            Nauru                     English, Nauru
FSM       Micronesia                            English
VUT          Vanuatu           Bislama, English, French
PLW            Palau                   English, Palauan
BHR          Bahrain                             Arabic

[201 rows x 2 columns]

**Ejercicios**

1. Defina una función llamada `obtener_capital_pais()` que reciba el código cca3 de un país y retorne su capital mediante una consulta al API REST Countries. Utilíce esta función para crear en el dataframe `paises` una nueva columna llamada `CAPITAL`, con la ciudad capital de cada país.

### Agrupación y agregación

El proceso de agrupación y agregación consiste en dividir un conjunto de datos en grupos basados en uno o más criterios, para luego realizar operaciones en cada grupo. En pandas, este proceso se realiza mediante el método [pandas.DataFrame.groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html).

Por ejemplo, el dataframe de países puede agruparse por continente para calcular en cada uno la suma de la población.

In [50]:
# Suma de población por continente
suma_poblacion_por_continente = paises.groupby('CONTINENT')['POP_EST'].sum()

# Despliegue de los resultados, ordenados descendentemente por población
suma_poblacion_por_continente.sort_values(ascending=False)

CONTINENT
Asia                      4,562,304,603.00
Africa                    1,307,986,092.30
Europe                      747,708,092.00
North America               584,776,221.00
South America               427,063,263.00
Oceania                      41,589,500.00
Seven seas (open ocean)       1,894,289.00
Antarctica                        4,490.00
Name: POP_EST, dtype: float64

El argumento de `groupby()` es usualmente una columna categórica (ej. `CONTINENT`) cuyos valores pasan a ser los grupos. En cada grupo se aplica una función de agregación (ej. `sum()`) para los valores de una columna numérica (ej. `POP_EST`).

Algunas funciones comunes de agregación son:

- `sum()`: suma.
- `mean()`: promedio.
- `count()`: número de elementos.
- `max()`, `min()`: valores máximo y mínimo.
- `median()`: mediana.
- `std()`: desviación estándar.
- `agg()`: para aplicar múltiples funciones o funciones personalizadas.

El método `groupby()` permite agrupar también por múltiples columnas.

In [51]:
# Suma de población por región y subregión de la ONU
suma_poblacion_por_region_subregion = paises.groupby(['REGION_UN', 'SUBREGION'])['POP_EST'].sum()

suma_poblacion_por_region_subregion

REGION_UN   SUBREGION
Africa      Eastern Africa                435,175,445.30
            Middle Africa                 174,308,432.00
            Northern Africa               241,801,558.00
            Southern Africa                66,629,895.00
            Western Africa                391,434,098.00
Americas    Caribbean                      38,982,419.00
            Central America               176,609,080.00
            Northern America              369,184,722.00
            South America                 427,063,263.00
Antarctica  Antarctica                          4,490.00
Asia        Central Asia                   73,814,587.00
            Eastern Asia                1,636,296,580.00
            South-Eastern Asia            661,911,038.00
            Southern Asia               1,918,690,648.00
            Western Asia                  272,122,703.00
Europe      Eastern Europe                291,080,093.00
            Northern Europe               105,802,448.00
            Southern Europe               152,729,852.00
            Western Europe                198,095,699.00
Oceania     Australia and New Zealand      30,319,695.00
            Melanesia                      10,635,767.00
            Micronesia                        320,801.00
            Polynesia                         313,237.00
Name: POP_EST, dtype: float64

También es posible aplicar múltiples funciones de agregación.

In [52]:
# Suma y promedio de población por región y subregión de la ONU
suma_promedio_poblacion_por_region_subregion = paises.groupby(['REGION_UN', 'SUBREGION'])['POP_EST'].agg(['sum', 'mean'])

suma_promedio_poblacion_por_region_subregion

                                                  sum           mean
REGION_UN  SUBREGION
Africa     Eastern Africa              435,175,445.30  22,903,970.81
           Middle Africa               174,308,432.00  19,367,603.56
           Northern Africa             241,801,558.00  34,543,079.71
           Southern Africa              66,629,895.00  13,325,979.00
           Western Africa              391,434,098.00  24,464,631.12
Americas   Caribbean                    38,982,419.00   2,998,647.62
           Central America             176,609,080.00  22,076,135.00
           Northern America            369,184,722.00 184,592,361.00
           South America               427,063,263.00  35,588,605.25
Antarctica Antarctica                        4,490.00       4,490.00
Asia       Central Asia                 73,814,587.00  14,762,917.40
           Eastern Asia              1,636,296,580.00 272,716,096.67
           South-Eastern Asia          661,911,038.00  60,173,730.73
           Southern Asia             1,918,690,648.00 213,187,849.78
           Western Asia                272,122,703.00  14,322,247.53
Europe     Eastern Europe              291,080,093.00  29,108,009.30
           Northern Europe             105,802,448.00  10,580,244.80
           Southern Europe             152,729,852.00   9,545,615.75
           Western Europe              198,095,699.00  22,010,633.22
Oceania    Australia and New Zealand    30,319,695.00  15,159,847.50
           Melanesia                    10,635,767.00   2,658,941.75
           Micronesia                      320,801.00      64,160.20
           Polynesia                       313,237.00     104,412.33

**Ejercicios**

1. Calcule el promedio del PIB (`GDP_MD`) por continente. Muestre los resultados por orden alfabético de continente.
2. Calcule la suma y el promedio del PIB (`GDP_MD`) por continente. Muestre los resultados por orden descendente de suma del PIB.
3. Calcule el promedio del PIB (`GDP_MD`) por grupo de ingresos (`INCOME_GRP`). Muestre los resultados en orden descendente de promedio del PIB.
4. Calcule el promedio del PIB (`GDP_MD`) para las subregiones de las regiones de la ONU del continente americano. Muestre los resultados en orden descendente de promedio del PIB.

### Unión (*join*)

La unión (en inglés, *join*) de datos ubicados en diferentes fuentes (ej. diferentes archivos) es una tarea común en análisis de información. Las uniones pueden ser de filas, columnas o de ambas. Usualmente, este tipo de operaciones se realiza con base en columnas que son comunes en los conjuntos de datos que se desea unir. A estas columnas se les llama "llaves" o "claves" (en inglés, *keys*).

Hay varios tipos de uniones de datos:

- ***Left join***: mantiene todas las filas del conjunto de datos del lado izquierdo y les agrega las columnas del conjunto de datos del lado derecho, en las filas en las que hay coincidencia en las llaves.
- ***Right join***: mantiene todas las filas del conjunto de datos del lado derecho y agrega las columnas del conjunto de datos del lado izquierdo, en las filas en las que hay coincidencia en las llaves.
- ***Inner join***: incluye las filas que coinciden en ambos conjuntos de datos.
- ***Full join***: incluye todas las filas de ambos conjuntos de datos.

Los diferentes tipos de unión se ilustran en la {numref}`figure-tipos-join` mediante diagramas de Venn.

```{figure} img/join.jpg
:name: figure-tipos-join

Tipos de uniones de datos. Imagen de [hostingplus](https://www.hostingplus.com.co/blog/tipos-de-join-en-sql-cuales-son-los-principales/).
```

La biblioteca pandas incluye varios métodos para unir series y dataframes:

- [`pandas.DataFrame.merge()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)
- [`pandas.DataFrame.join()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html)
- [`pandas.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

Para ejemplificar el concepto de unión de datos, al dataframe `paises` se le agregará una columna correspondiente a la [esperanza de vida al nacer](https://es.wikipedia.org/wiki/Esperanza_de_vida) en cada país. Esta columna proviene de los datos de [indicadores del Banco Mundial](https://datos.bancomundial.org/indicador).

In [53]:
# Carga de datos de esperanza de vida al nacer por país

esperanza_vida = pd.read_csv(
    "https://raw.githubusercontent.com/pf3311-cienciadatosgeoespaciales/2025-ii/refs/heads/main/datos/world-bank/paises-esperanza-vida.csv"
)

El archivo CSV del Banco Mundial tiene más de 60 columnas. Para simplificar el análisis, se conservan solamente las columnas `Country Code` (código cca3) y `2022` (esperanza de vida al nacer en 2022). La primera se utiliza como índice.

In [54]:
# Reducción de columnas de esperanza_vida
esperanza_vida = esperanza_vida[['Country Code', '2022']]

# Se usa la columna 'Country Code' como índice
esperanza_vida.set_index('Country Code', inplace=True)

# Muestra de los datos
esperanza_vida.sample(10)

              2022
Country Code
PSE          73.44
GTM          68.67
ARB          71.23
AFE          62.90
PHL          72.19
ARM          73.37
NAC          77.84
LMY          70.40
TSS          60.76
COL          73.66

Seguidamente, se utiliza el método `pandas.Dataframe.join()` para unir `paises` con `paises_esperanza_vida`. Se elige este método debido a que su sintaxis es muy sencilla cuando las llaves de ambos dataframes con los índices.

In [55]:
# Unión de los dataframes paises y esperanza_vida
paises = paises.join(esperanza_vida, how="left")

En este caso `paises` es el conjunto del "lado izquierdo" y `esperanza_vida` el del "lado derecho". El argumento `how="left"` indica que se está realizando un *left join*, por lo que se conservan todas las filas del conjunto de lado izquierdo. Si el código cca3 de algún país de `países` no está en `esperanza_vida`, la columna unida tendrá un valor nulo.

La nueva columna se renombra con el método [`pandas.DataFrame.rename()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html), para que sea similar a las otras.

In [56]:
# Cambio de nombre de la nueva columna

paises.rename(columns={'2022': 'LIFE_EXPECTANCY'}, inplace=True)

In [57]:
# Muestra aleatoria de 10 filas
paises.sample(5)

,NAME,CONTINENT,REGION_UN,SUBREGION,REGION_WB,ECONOMY,INCOME_GRP,POP_EST,GDP_MD,GDP_PC,LANGUAGES,LIFE_EXPECTANCY
ADM0_ISO,,,,,,,,,,,,
LIE,Liechtenstein,Europe,Europe,Western Europe,Europe & Central Asia,2. Developed region: nonG7,2. High income: nonOECD,"38,019.00",6876,"180,856.94",German,84.32
BLR,Belarus,Europe,Europe,Eastern Europe,Europe & Central Asia,6. Developing region,3. Upper middle income,"9,466,856.00",63080,"6,663.25","Belarusian, Russian",73.11
CRI,Costa Rica,North America,Americas,Central America,Latin America & Caribbean,5. Emerging region: G20,3. Upper middle income,"5,047,561.00",61801,"12,243.74",Spanish,77.32
STP,São Tomé and Principe,Africa,Africa,Middle Africa,Sub-Saharan Africa,7. Least developed region,4. Lower middle income,"215,056.00",418,"1,943.68",Portuguese,68.79
MKD,North Macedonia,Europe,Europe,Southern Europe,Europe & Central Asia,6. Developing region,3. Upper middle income,"2,083,459.00",12547,"6,022.20",Macedonian,74.42

In [58]:
# Países con esperanza de vida más alta
paises.sort_values(by='LIFE_EXPECTANCY', ascending=False).head(10)[['NAME', 'CONTINENT', 'LIFE_EXPECTANCY']]

                   NAME CONTINENT  LIFE_EXPECTANCY
ADM0_ISO
LIE       Liechtenstein    Europe            84.32
JPN               Japan      Asia            84.00
CHE         Switzerland    Europe            83.45
AUS           Australia   Oceania            83.20
SWE              Sweden    Europe            83.11
ESP               Spain    Europe            83.08
IRL             Ireland    Europe            83.06
LUX          Luxembourg    Europe            83.05
ITA               Italy    Europe            82.90
SGP           Singapore      Asia            82.90

In [59]:
# Países con esperanza de vida más baja
paises.sort_values(by='LIFE_EXPECTANCY', ascending=True).head(10)[['NAME', 'CONTINENT', 'LIFE_EXPECTANCY']]

                          NAME CONTINENT  LIFE_EXPECTANCY
ADM0_ISO
TCD                       Chad    Africa            53.00
LSO                    Lesotho    Africa            53.04
NGA                    Nigeria    Africa            53.63
CAF       Central African Rep.    Africa            54.48
SSD                   S. Sudan    Africa            55.57
SOM                 Somaliland    Africa            56.11
SOM                    Somalia    Africa            56.11
SWZ                   eSwatini    Africa            56.36
NAM                    Namibia    Africa            58.06
CIV              Côte d'Ivoire    Africa            58.92

**Ejercicios**

1. Mediante uniones de datos, agregue al dataframe `paises` columnas correspondientes a:
   
  - Tasa de alfabetización de adultos.
  - Tasa de mortalidad infantil.
  
  Busque los archivos de datos necesarios en [Banco Mundial - Datos de indicadores](https://datos.bancomundial.org/indicador). **Sugerencia**: con un editor de texto (ej. VS Code) elimine las filas que no forman parte del formato CSV en la parte superior de los archivos.

### Manejo de valores nulos

Como se mencionó, el *left join* puede producir valores nulos (`NaN`) en la columna `LIFE_EXPECTANCY` para los países cuyo código cca3 no se encuentra en `esperanza_vida`. pandas ofrece varios métodos para detectar y manejar estos valores.

El método [`pandas.DataFrame.isna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) (y su alias `isnull()`) retorna un dataframe booleano del mismo tamaño que el original, donde `True` indica que el valor es nulo. Combinado con `sum()`, permite contar los valores nulos por columna:

In [60]:
# Conteo de valores nulos por columna

paises.isna().sum()

NAME                0
CONTINENT           0
REGION_UN           0
SUBREGION           0
REGION_WB           0
ECONOMY             0
INCOME_GRP          0
POP_EST             0
GDP_MD              0
GDP_PC              0
LANGUAGES           5
LIFE_EXPECTANCY    11
dtype: int64

También puede utilizarse como máscara booleana para filtrar las filas con nulos en una columna específica:

In [61]:
# Países con valor nulo en LIFE_EXPECTANCY

paises[paises['LIFE_EXPECTANCY'].isna()][['NAME', 'CONTINENT']]

                      NAME   CONTINENT
ADM0_ISO
B28              W. Sahara      Africa
SDZ                  Sudan      Africa
SMR             San Marino      Europe
MCO                 Monaco      Europe
AND                Andorra      Europe
PR1               Portugal      Europe
PN1       Papua New Guinea     Oceania
VAT                Vatican      Europe
ATA             Antarctica  Antarctica
TWN                 Taiwan        Asia
PLW                  Palau     Oceania

Las dos estrategias más comunes para manejar valores nulos son **eliminarlos** o **reemplazarlos**.

El método [`pandas.DataFrame.dropna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) elimina las filas que contienen al menos un valor nulo. Con el argumento `subset` puede limitarse la búsqueda a columnas específicas:

In [62]:
# Dataframe sin las filas con LIFE_EXPECTANCY nulo

paises_sin_nulos = paises.dropna(subset=['LIFE_EXPECTANCY'])
paises_sin_nulos.shape

(190, 12)

El método [`pandas.DataFrame.fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) reemplaza los valores nulos por un valor indicado. Por ejemplo, puede usarse la media de la columna:

In [63]:
# Dataframe con los nulos de LIFE_EXPECTANCY rellenados con la media

media_esperanza = paises['LIFE_EXPECTANCY'].mean()
paises_rellenos = paises.fillna({'LIFE_EXPECTANCY': media_esperanza})

# Verificación: ya no hay nulos en LIFE_EXPECTANCY
paises_rellenos['LIFE_EXPECTANCY'].isna().sum()

np.int64(0)

La decisión entre eliminar o reemplazar los valores nulos depende del contexto del análisis: eliminar reduce el tamaño del conjunto y puede sesgar los resultados, mientras que reemplazar introduce valores sintéticos que pueden afectar las estadísticas posteriores.

### Exportación

pandas proporciona varios métodos para exportar dataframes a otros formatos. Por ejemplo, el método [`pandas.DataFrame.to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) exporta un dataframe a un archivo de valores separados por comas (CSV). Otros métodos similares pueden exportar a otros formatos.

In [64]:
# Exportación al formato CSV
paises.to_csv('paises-ampliado.csv')

# Exportación al formato JSON
paises.to_json('paises-ampliado.json', orient='records')

## Recursos de interés

*Banco Mundial - Datos de indicadores*. (s. f.). Recuperado 6 de octubre de 2024, de [https://datos.bancomundial.org/indicador](https://datos.bancomundial.org/indicador)
\
\
*Natural Earth - Free vector and raster map data*. (s. f.). Recuperado 6 de octubre de 2024, de [https://www.naturalearthdata.com/](https://www.naturalearthdata.com/)
\
\
*REST Countries - Get information about countries via a RESTful API*. (s. f.). Recuperado 24 de abril de 2026, de [https://restcountries.com/](https://restcountries.com/)